/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HostalesRouteImport } from './routes/hostales'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as TaxisRouteImport } from './routes/taxis'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminBidsRouteImport } from './routes/admin.bids'
import { Route as PrestadoresDashboardRouteImport } from './routes/prestadores.dashboard'
import { Route as PrestadoresRegistroRouteImport } from './routes/prestadores.registro'
import { Route as PropiedadSlugRouteImport } from './routes/propiedad.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HostalesRoute = HostalesRouteImport.update({
  id: '/hostales',
  path: '/hostales',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxisRoute = TaxisRouteImport.update({
  id: '/taxis',
  path: '/taxis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBidsRoute = AdminBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => AdminRoute,
} as any)
const PrestadoresDashboardRoute = PrestadoresDashboardRouteImport.update({
  id: '/prestadores/dashboard',
  path: '/prestadores/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestadoresRegistroRoute = PrestadoresRegistroRouteImport.update({
  id: '/prestadores/registro',
  path: '/prestadores/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadSlugRoute = PropiedadSlugRouteImport.update({
  id: '/propiedad/$slug',
  path: '/propiedad/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/hostales': typeof HostalesRoute
  '/restaurantes': typeof RestaurantesRoute
  '/taxis': typeof TaxisRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bids': typeof AdminBidsRoute
  '/prestadores/dashboard': typeof PrestadoresDashboardRoute
  '/prestadores/registro': typeof PrestadoresRegistroRoute
  '/propiedad/$slug': typeof PropiedadSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hostales': typeof HostalesRoute
  '/restaurantes': typeof RestaurantesRoute
  '/taxis': typeof TaxisRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bids': typeof AdminBidsRoute
  '/prestadores/dashboard': typeof PrestadoresDashboardRoute
  '/prestadores/registro': typeof PrestadoresRegistroRoute
  '/propiedad/$slug': typeof PropiedadSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/hostales': typeof HostalesRoute
  '/restaurantes': typeof RestaurantesRoute
  '/taxis': typeof TaxisRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bids': typeof AdminBidsRoute
  '/prestadores/dashboard': typeof PrestadoresDashboardRoute
  '/prestadores/registro': typeof PrestadoresRegistroRoute
  '/propiedad/$slug': typeof PropiedadSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/hostales'
    | '/restaurantes'
    | '/taxis'
    | '/admin/banners'
    | '/admin/bids'
    | '/prestadores/dashboard'
    | '/prestadores/registro'
    | '/propiedad/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/hostales'
    | '/restaurantes'
    | '/taxis'
    | '/admin/banners'
    | '/admin/bids'
    | '/prestadores/dashboard'
    | '/prestadores/registro'
    | '/propiedad/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/hostales'
    | '/restaurantes'
    | '/taxis'
    | '/admin/banners'
    | '/admin/bids'
    | '/prestadores/dashboard'
    | '/prestadores/registro'
    | '/propiedad/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  HostalesRoute: typeof HostalesRoute
  RestaurantesRoute: typeof RestaurantesRoute
  TaxisRoute: typeof TaxisRoute
  PrestadoresDashboardRoute: typeof PrestadoresDashboardRoute
  PrestadoresRegistroRoute: typeof PrestadoresRegistroRoute
  PropiedadSlugRoute: typeof PropiedadSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostales': {
      id: '/hostales'
      path: '/hostales'
      fullPath: '/hostales'
      preLoaderRoute: typeof HostalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxis': {
      id: '/taxis'
      path: '/taxis'
      fullPath: '/taxis'
      preLoaderRoute: typeof TaxisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bids': {
      id: '/admin/bids'
      path: '/bids'
      fullPath: '/admin/bids'
      preLoaderRoute: typeof AdminBidsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/prestadores/dashboard': {
      id: '/prestadores/dashboard'
      path: '/prestadores/dashboard'
      fullPath: '/prestadores/dashboard'
      preLoaderRoute: typeof PrestadoresDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestadores/registro': {
      id: '/prestadores/registro'
      path: '/prestadores/registro'
      fullPath: '/prestadores/registro'
      preLoaderRoute: typeof PrestadoresRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedad/$slug': {
      id: '/propiedad/$slug'
      path: '/propiedad/$slug'
      fullPath: '/propiedad/$slug'
      preLoaderRoute: typeof PropiedadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBidsRoute: typeof AdminBidsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminBidsRoute: AdminBidsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  HostalesRoute: HostalesRoute,
  RestaurantesRoute: RestaurantesRoute,
  TaxisRoute: TaxisRoute,
  PrestadoresDashboardRoute: PrestadoresDashboardRoute,
  PrestadoresRegistroRoute: PrestadoresRegistroRoute,
  PropiedadSlugRoute: PropiedadSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
