/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HostalesRouteImport } from './routes/hostales'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as TaxisRouteImport } from './routes/taxis'
import { Route as PrestadoresRegistroRouteImport } from './routes/prestadores.registro'
import { Route as PropiedadSlugRouteImport } from './routes/propiedad.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HostalesRoute = HostalesRouteImport.update({
  id: '/hostales',
  path: '/hostales',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxisRoute = TaxisRouteImport.update({
  id: '/taxis',
  path: '/taxis',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestadoresRegistroRoute = PrestadoresRegistroRouteImport.update({
  id: '/prestadores/registro',
  path: '/prestadores/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadSlugRoute = PropiedadSlugRouteImport.update({
  id: '/propiedad/$slug',
  path: '/propiedad/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hostales': typeof HostalesRoute
  '/restaurantes': typeof RestaurantesRoute
  '/taxis': typeof TaxisRoute
  '/prestadores/registro': typeof PrestadoresRegistroRoute
  '/propiedad/$slug': typeof PropiedadSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hostales': typeof HostalesRoute
  '/restaurantes': typeof RestaurantesRoute
  '/taxis': typeof TaxisRoute
  '/prestadores/registro': typeof PrestadoresRegistroRoute
  '/propiedad/$slug': typeof PropiedadSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hostales': typeof HostalesRoute
  '/restaurantes': typeof RestaurantesRoute
  '/taxis': typeof TaxisRoute
  '/prestadores/registro': typeof PrestadoresRegistroRoute
  '/propiedad/$slug': typeof PropiedadSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/hostales'
    | '/restaurantes'
    | '/taxis'
    | '/prestadores/registro'
    | '/propiedad/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/hostales'
    | '/restaurantes'
    | '/taxis'
    | '/prestadores/registro'
    | '/propiedad/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/hostales'
    | '/restaurantes'
    | '/taxis'
    | '/prestadores/registro'
    | '/propiedad/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HostalesRoute: typeof HostalesRoute
  RestaurantesRoute: typeof RestaurantesRoute
  TaxisRoute: typeof TaxisRoute
  PrestadoresRegistroRoute: typeof PrestadoresRegistroRoute
  PropiedadSlugRoute: typeof PropiedadSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostales': {
      id: '/hostales'
      path: '/hostales'
      fullPath: '/hostales'
      preLoaderRoute: typeof HostalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxis': {
      id: '/taxis'
      path: '/taxis'
      fullPath: '/taxis'
      preLoaderRoute: typeof TaxisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestadores/registro': {
      id: '/prestadores/registro'
      path: '/prestadores/registro'
      fullPath: '/prestadores/registro'
      preLoaderRoute: typeof PrestadoresRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedad/$slug': {
      id: '/propiedad/$slug'
      path: '/propiedad/$slug'
      fullPath: '/propiedad/$slug'
      preLoaderRoute: typeof PropiedadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HostalesRoute: HostalesRoute,
  RestaurantesRoute: RestaurantesRoute,
  TaxisRoute: TaxisRoute,
  PrestadoresRegistroRoute: PrestadoresRegistroRoute,
  PropiedadSlugRoute: PropiedadSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
